### PR TITLE
Completely replace logging infrastructure with zf_log

### LINKED ISSUE #71: Overhaul or replace logging framework
(Continued from discussion in [#50](https://github.com/pflarue/ardop/pull/50#pullrequestreview-2159370820))

The existing console and file logging framework has some issues:

* Mismatched `printf()` format strings and arguments. Functions like `Debugprintf()` did not take advantage of GCC's `__printflike` attribute to check format codes. Some invocations had missing arguments that would lead to UB and probably crashes.

* Use of unsafe unbounded `sprintf()` and `strcat()` functions. These need to be replaced.

* The logger should be split into its own header and object file. Right now:

  * Symbols are declared in `ardopcommon.h`, which has a lot of other unrelated stuff.

  * The implementation is part of the platform-specific code. This may introduce unwanted platform-specific differences.

  * Global variables are mixed with other, unrelated symbols.

If you don't mind the logs looking a bit different, it may be more expeditious and safer to replace the logger with something like [zf_log](https://github.com/wonder-mice/zf_log) or [rxi/log.c](https://github.com/rxi/log.c). Of these, zf_log looks much more mature. Both are pure C, require no build system, and are MIT-licensed. There are undoubtedly many others.

### PR DESCRIPTION
**Pull request by cbs228**
The legacy logger has known issues which are summarized in #71. Some of these could lead to UB and crashes. Replace the logger with [zf_log](https://github.com/wonder-mice/zf_log). This also corrects all `printf()` format warnings reported by gcc 13. A few of these warnings were serious and could potentially lead to crashes.

Besides bugfixes, the following new functionality is introduced:

* **breaking CLI option changes**: the deprecated `-v` and `-V` verbosity switches are removed. Use `-H` host commands instead. Add a new `-m`|`--nologfile` option to suppress file output.

* **automatic rollover**: ardopcf now switches to a new log file at UTC midnight. This permits the use of [logrotate(8)](https://linux.die.net/man/8/logrotate) or other programs to remove old log files.

* **debug log decoration**: the ARDOPDebug log uses zf_log-style timestamps and includes the log level. The format is slightly different.

* **session log time**: the ARDOPSession log now uses an ISO 8601 timestamp

* **cross-platform logging**: log processing is no longer part of platform-specific source files

Now for the quirks:

* The `CONSOLELOG` and `FILELEVEL` TNC commands now use zf_log log levels instead of the legacy syslog-esque levels. This is API-BREAKING behavior for non-standard TNC commands.

* While zf_log has fewer verbosity levels than legacy ardopc, it has enough levels for our purpose. The following verbosity levels are removed:

  * `LOGEMERGENCY` was not used anywhere. Using this level now just disables logs, which is what it did before.

  * `LOGCRIT` and `LOGALERT` are mapped to `ZF_LOGF` ("fatal")

  * `LOGNOTICE` was not used anywhere

  If we want more granularity, we might prefer log "tags" for individual modules instead of trying to add more log levels.

* If ardopcf is compiled in release mode (`-O3 -DNDEBUG`), the "verbose" log level is compiled out and will never be output. This increases speed of release-mode builds at the expense of output options. We can disable this behavior if you want.

* The new logger is almost certainly not suitable for multithreaded programs. zf_log itself appears to be, but our add-on behavior should be presumed racy. We'll have to address this if we ever want to multi-thread.

This PR is huge. You can reduce the diffs by applying the following commands:

<details>
<summary>Click to view</summary>

```bash
# add zf_log from github
git subtree add --squash -P lib/zf_log \
  https://github.com/wonder-mice/zf_log.git \
  5a3f2b46c3f62b97e2b33fbdb9d391abb64644f7

# apply zf_log patch
curl -L 'https://github.com/pflarue/zf_log/commit/bcc7fe02bbd812aa88578f106b17d3fab8415c6b.patch' >/tmp/time-utc-option.patch
git am --directory=lib/zf_log /tmp/time-utc-option.patch

# add mustuse.h from #79, which you have already
# reviewed
git format-patch --stdout -1 \
  8b771d2f9103f11ac3ccd8754fb5923d6a91bfd9 \
  -- src/common/mustuse.h | \
    git am

# reproduce find and replace for new log API
find src -iname '*.c' -exec \
  sed -i -r \
    -e 's/WriteDebugLog\(\s*LOG(CRIT|ALERT)\s*,\s*/ZF_LOGF(/g' \
    -e 's/WriteDebugLog\(\s*LOGERROR\s*,\s*/ZF_LOGE(/g' \
    -e 's/WriteDebugLog\(\s*LOGWARNING\s*,\s*/ZF_LOGW(/g' \
    -e 's/WriteDebugLog\(\s*LOGINFO\s*,\s*/ZF_LOGI(/g' \
    -e 's/WriteDebugLog\(\s*LOGDEBUG\s*,\s*/ZF_LOGD(/g' \
    -e 's/WriteDebugLog\(\s*LOGDEBUGPLUS\s*,\s*/ZF_LOGV(/g' \
    -e 's/sprintf\s*\(\s*(HostCmd|strFault),\s*"/snprintf(\1, sizeof(\1), "/g' \
    \{\} \;
git commit -m 'Reproduce find and replace'
```
</details>

Closes #71

Blocks #79

### CODE REVIEW

**Comment by pflarue** [comment]
I'm back from some time with limited Internet connectivity.  I've read through the comments on this and the prior PRs, but haven't yet look at the code.  I'll be spending some time on these in the next few days. 

So far, the only thing that concerns me is the handling of UTC date/time.  It sounds like you've implemented a workaround to make this work.  Using UTC is important to me since it allows convenient comparison of logs generated by communicating stations which when communicating over HF may often be in different time zones.  Those communicating stations may also be running different Ardop implementations.  Amateur radio operators generally use UTC for contact logging, so compatibility with those logs is also valuable.  So  I'll look closely at this.

I've found the ability to adjust the log level without restarting ardopcf to be useful to temporarily turn up the log level for testing purposes, and then return it to a lower level for normal use.  I think that this would be particularly valuable if ardopcf were to be used as a long running process.  I plan to revisit the CODEC, PLAYBACK, and CAPTURE host commands to better facilitate this mode of use while allowing reduced use of system resources while inactive.  Such changes would make using ardopcf on a headless SBC more convenient by allowing more complete control of the program via a host interface or the WebGui.  It would be nice if logging in to the computer's console wasn't required for normal use.

That said, I'm open to also retaining the -v and -V command line options if you can suggest a reason to retain them.  I have marked all options whose functionality was duplicated by the --hostcommands option as deprecated.  In the case of -v and -V, I recognized that this slightly delays the setting of these levels, but didn't see that as a significant problem.  I welcome further discussion on this topic.

I don't anticipate the lack of multithreading support or reduced level granularity will be problems.  I expect ardopcf to remain a single threaded program.  While some adjustment of level settings associated with specific log messages may be appropriate, the lack of use of some previously defined levels suggests that we should be able to accommodate a reduction in the number of available levels.

**Comment by cbs228** [comment]
>  Amateur radio operators generally use UTC for contact logging, so compatibility with those logs is also valuable.

I wonder if ADIF output would be useful. But that's a problem for later.

> I've found the ability to adjust the log level without restarting ardopcf to be useful to temporarily turn up the log level for testing purposes

This is certainly very useful. I was speaking more about the `DEBUGLOG` command which starts and stops all file logging. This can already be done by adjusting the log level.

> I'm open to also retaining the -v and -V command line options if you can suggest a reason to retain them

I think that verbosity options are right up there with `--help` and `--version` when it comes to standard behavior for CLI programs and daemons. Right now, the only way to prevent a log file from being written is to either use `-v 0` or to set `--logdir /dev/null`, and the latter causes a warning. I think this is a fairly compelling use-case:

* If I was going to deploy ardopcf as an RMS or other server node, I would probably opt to use systemd and just use the journal for logs. In that case, separate console logs are completely superfluous.

* Many SBCs and some desktops don't run systemd, but almost all of them support `syslog()`.

On that note, we should probably add a `--syslog` option that replaces the stdout console log with `syslog()` when enabled. zf_log has examples of this; it wouldn't be hard. WDYT? That would be a task for a future PR, not now. It would also be a Linux-only option. Alternatively, we could design a console formatter specifically for journald, but this may be less useful.

Users running `ardopcf` interactively will probably want regular logs, and regular log files are great for troubleshooting reports from end users. So they are here to stay!

**Comment by cbs228** [comment]
cf06c51b26f2a65cdf7a01ddb77c030d735e848f rebases to fix conflicts. There should be no diffs from the previous version. (See the [compare](https://github.com/pflarue/ardop/compare/27dee024e1ba804a3bf252e962aec3cb194a5f67..cf06c51b26f2a65cdf7a01ddb77c030d735e848f) button for interdiffs.)

File: lib/zf_log/zf_log/zf_log.c [hunk 1]
```diff
@@ -0,0 +1,1389 @@
...
+	{
+		g_tcache_tv = *tv;
+		g_tcache_tm = *tm;
+		__atomic_and_fetch(&g_tcache_mode, ~TCACHE_FLUID, __ATOMIC_RELEASE);
+	}
+}
+#endif
+
+static void time_callback(struct tm *const tm, unsigned *const msec)
+{
```
Comment (pflarue) [inline lib/zf_log/zf_log/zf_log.c:802]: See the time-utc-option branch of https://github.com/pflarue/zf_log.  This includes some minor changes from https://github.com/wonder-mice/zf_log which allow UTC time rather than local time to be used for both Windows and Linux.  The workaround used by this pull request did not produce UTC timestamps on Windows.

File: src/common/ARDOPC.c [hunk 2]
```diff
@@ -1172,7 +1168,7 @@ BOOL FrameInfo(UCHAR bytFrameType, int * blnOdd, int * intNumCar, char * strMod,
 			break;
 
 		default:
-			WriteDebugLog(LOGCRIT, "No data for frame type = 0x" ,bytFrameType);
+			ZF_LOGW("No data for frame type = 0x%02hhx", bytFrameType);
```
Comment (pflarue) [inline src/common/ARDOPC.c]: This should be ZF_LOGE not ZF_LOGW because this indicates a serious logic error.

File: src/common/ARDOPCommon.c [hunk 3]
```diff
@@ -7,6 +7,8 @@
 //   of version numbers pushed to git repository.
 #include "common/version.h"
 
+#define _POSIX_C_SOURCE 200809L
+
```
Comment (pflarue) [inline src/common/ARDOPCommon.c]: With the other changes I am suggesting, this is not needed.

File: src/common/ARDOPCommon.c [hunk 4]
```diff
@@ -518,6 +500,26 @@ void processargs(int argc, char * argv[])
...
 	}
+
+	// Set this program's time zone to UTC
+	// This MUST occur before we start logging
+#if defined(_WIN32) || defined(_WIN64)
+	_putenv("TZ=UTC+0");
+#else
+	setenv("TZ", "UTC+0", 1);
+#endif
+	tzset();
```
Comment (pflarue) [inline src/common/ARDOPCommon.c]: Using time-utc-option branch of zf_log, this isn't needed.

File: src/common/ARQ.c [hunk 5]
```diff
@@ -1949,25 +1937,25 @@ void ProcessRcvdARQFrame(UCHAR intFrameType, UCHAR * bytData, int DataLen, BOOL
...
 
-				if (intFrameType >= DataACKmin && DebugLog)
-					WriteDebugLog(LOGINFO, "[ARDOPprotocol.ProcessRcvdARQFrame] ACK received in ARQState %s ", ARQSubStates[ARQState]);
+				if (intFrameType >= DataACKmin)
+					ZF_LOGD("[ARDOPprotocol.ProcessRcvdARQFrame] ACK received in ARQState %s ", ARQSubStates[ARQState]);
 
-				if (intFrameType == BREAK && DebugLog)
-					WriteDebugLog(LOGINFO, "[ARDOPprotocol.ProcessRcvdARQFrame] BREAK received in ARQState %s Processed as implied ACK", ARQSubStates[ARQState]);
+				if (intFrameType == BREAK)
+					ZF_LOGD("[ARDOPprotocol.ProcessRcvdARQFrame] BREAK received in ARQState %s Processed as implied ACK", ARQSubStates[ARQState]);
```
Comment (pflarue) [inline src/common/ARQ.c]: I think that both of these should be ZF_LOGI()

File: src/common/HostInterface.c [hunk 6]
```diff
@@ -430,22 +429,25 @@ void ProcessCommandFromHost(char * strCMD)
...
-
-			if (i >= LOGEMERGENCY  && i <= LOGDEBUGPLUS)
-			{
-				ConsoleLogLevel = i;
-				sprintf(cmdReply, "%s now %d", strCMD, ConsoleLogLevel);
-				SendReplyToHost(cmdReply);
-				WriteDebugLog(LOGALERT, "ConsoleLogLevel = %d (%s)", ConsoleLogLevel, strLogLevels[ConsoleLogLevel]);
-			}
-			else
-				sprintf(strFault, "Syntax Err: %s %s", strCMD, ptrParams);
```
Comment (pflarue) [inline src/common/HostInterface.c:448]: This is a change in behavior w.r.t. host programs.  While I'm OK with changing the level to what is probably a reasonable value, I'd prefer to also send an error to the host program.   What if ardop_log_set_level_console() returned a boolean indicating whether the the input value was valid.  This could be used to control which message should be sent to the host.

File: src/common/HostInterface.c [hunk 7]
```diff
@@ -778,22 +783,25 @@ void ProcessCommandFromHost(char * strCMD)
...
-
-			if (i >= LOGEMERGENCY  && i <= LOGDEBUGPLUS)
-			{
-				FileLogLevel = i;
-				sprintf(cmdReply, "%s now %d", strCMD, FileLogLevel);
-				SendReplyToHost(cmdReply);
-				WriteDebugLog(LOGALERT, "FileLogLevel = %d (%s)", FileLogLevel, strLogLevels[FileLogLevel]);
-			}
-			else
-				sprintf(strFault, "Syntax Err: %s %s", strCMD, ptrParams);
```
Comment (pflarue) [inline src/common/HostInterface.c:796]: This is a change in behavior w.r.t. host programs. While I'm OK with changing the level to what is probably a reasonable value, I'd prefer to also send an error to the host program. What if ardop_log_set_level_file() returned a boolean indicating whether the the input value was valid. This could be used to control which message should be sent to the host.

File: test/ardop/setup.c [hunk 8]
```diff
@@ -1,10 +1,14 @@
 #include "setup.h"
 
-// log level constants
-extern int FileLogLevel;
-extern int ConsoleLogLevel;
+#define _POSIX_C_SOURCE 200809L
```
Comment (pflarue) [inline test/ardop/setup.c]: With the other suggested changes, this isn't required.

File: test/ardop/setup.c [hunk 9]
```diff
@@ -1,10 +1,14 @@
...
 
 void ardop_test_setup() {
-    FileLogLevel = 0;
-    ConsoleLogLevel = 0;
+#if defined(_WIN32) || defined(_WIN64)
+	_putenv("TZ=UTC+0");
+#else
+	setenv("TZ", "UTC+0", 1);
+#endif
+	tzset();
```
Comment (pflarue) [inline test/ardop/setup.c]: With use of time-utc-option branch of zf_log this is not needed.

File: test/ardop/test_log.c [hunk 10]
```diff
@@ -0,0 +1,241 @@
...
+
+	// with overflow
+	ok = ardop_logfile_calc_filename(&uut, UNIX_TIME, filename, 4);
+	assert_false(ok);
+
+	// with directory
+	ardop_logfile_init(&uut, "out", "mylog", ".txt", 6663);
+	ok = ardop_logfile_calc_filename(&uut, UNIX_TIME, filename, sizeof(filename));
+	assert_true(ok);
+	assert_string_equal(filename, "out" ARDOP_PLATFORM_PATHSEP "mylog6663_20240803_UTC.txt");
```
Comment (pflarue) [inline test/ardop/test_log.c]: If `_UTC` is removed from filenames as suggested, edits are required throughout this file.

File: src/common/log.c [hunk 11]
```diff
@@ -0,0 +1,318 @@
...
+
+#include "common/log_file.h"
+
+// Configure log decoration, see zf_log.c
+#define ZF_LOG_MESSAGE_CTX_FORMAT (\
+	DAY, S(ZF_LOG_DEF_DELIMITER), \
+	HOUR, S(":"), MINUTE, S(":"), SECOND, S("."), MILLISECOND, S(ZF_LOG_DEF_DELIMITER), \
+	PID, S(ZF_LOG_DEF_DELIMITER), S(ZF_LOG_DEF_DELIMITER), \
+	LEVEL, S(ZF_LOG_DEF_DELIMITER) \
+)
```
Comment (pflarue) [inline src/common/log.c]: This puts a lot of info at the start of each line, often pushing much of the main text off screen to the right, thus making it hard to visually scan the logfile for relevant info.  I propose the following instead:
```
// If the following line is omitted, then the file location (function name,
// file name, line number) where each log message originates will be written
// to the log file.
#define ZF_LOG_MESSAGE_SRC_FORMAT ()

#define ZF_LOG_MESSAGE_CTX_FORMAT (\
        HOUR, S(":"), MINUTE, S(":"), SECOND, S("."), MILLISECOND, S(ZF_LOG_DEF_DELIMITER), \
        LEVEL, S(ZF_LOG_DEF_DELIMITER) \
 )
```
While location of log statements might be useful while actively trying to debug a specific problem, I think it is overkill for normal logging.  Most log statements are sufficiently unique that grep can be used to find the file it was written from, and then find/search in a text editor finds the relevant statement.  I suggest including the comment as a reminder that this information can easily be toggled on if desired.
 
Since `DAY` is part of the filename, there is no reason to include it here.  I also don't see the value of including PID.  However, I do like the addition of `LEVEL` to what was previously used.

File: src/common/log.c [hunk 12]
```diff
@@ -0,0 +1,318 @@
...
+#include <string.h>
+
+#if defined(_WIN32) || defined(_WIN64)
+#include <windows.h>
+#else
+#include <unistd.h>
+#endif
+
+#include "common/log_file.h"
+
```
Comment (pflarue) [inline src/common/log.c:12]: Along with using the time-utc-option branch of zf_log from https://github.com/pflarue/zf_log, insert the following two lines here to reliably get UTC timestamps in the log file:
```
// Use UTC time rather than local time in log files.
#define ZF_LOG_USE_UTC_TIME 1
```

File: src/common/log.c [hunk 13]
```diff
@@ -0,0 +1,318 @@
...
+	0,
+	NULL
+};
+
+static ArdopLogFile* ALL_LOG_FILES[] = {
+	&DebugLog,
+	&SessionLog
+};
+
+static void log_callback_discard(const zf_log_message*, void*) {}
```
Comment (pflarue) [inline src/common/log.c]: Slightly older C compilers require produce a parameter name omitted error here.  Change it to:
`static void log_callback_discard(const zf_log_message* msg, void* param) {}`

File: src/common/log.c [hunk 14]
```diff
@@ -0,0 +1,318 @@
...
+	if (!ZF_LOG_ON_INFO)
+		return;
+
+	char datefmt[32] = "";
+
+	// convert time_t to calendar time
+	struct tm cal;
+	localtime_r(&now->tv_sec, &cal);
+	// 2024-08-10T17:57:36
+	strftime(datefmt, sizeof(datefmt), "%Y-%m-%dT%H:%M:%S", &cal);
```
Comment (pflarue) [inline src/common/log.c]: Rather than override TZ and use localtime_r(), use gmtime() as follows:
```
struct tm *cal;
cal = gmtime(&now->tv_sec);
 // 2024-08-10T17:57:36
 strftime(datefmt, sizeof(datefmt), "%Y-%m-%dT%H:%M:%S", cal);
```

File: src/common/log.h [hunk 15]
```diff
@@ -0,0 +1,336 @@
...
+#define ARDOP_COMMON_LOG_H_
+
+#include <stdarg.h>
+#include <stdbool.h>
+#include <stdint.h>
+#include <stdio.h>
+#include <stddef.h>
+
+// for localtime_r()
+#define _POSIX_C_SOURCE 200809L
```
Comment (pflarue) [inline src/common/log.h]: With the other suggested changes, this is not required.

File: src/common/log_file.c [hunk 16]
```diff
@@ -0,0 +1,167 @@
...
+	char* out,
+	const size_t outsize
+) {
+	// convert time_t to calendar time
+	struct tm cal;
+	localtime_r(&now, &cal);
+
+	// format time
+	char cal_fmt[32];
+	strftime(cal_fmt, sizeof(cal_fmt), "%Y%m%d_%Z", &cal);
```
Comment (pflarue) [inline src/common/log_file.c]: Rather than override TZ and use localtime_r(), use gmtime() as follows:
```
struct tm *cal;
cal = gmtime(&now);

// format time
char cal_fmt[32];
strftime(cal_fmt, sizeof(cal_fmt), "%Y%m%d", cal);
```
Notice that I removed `_%Z` from the end of the format string to also eliminate `_UTC` from the filename.  As noted below, this requires several edits to test_log.c.

File: src/common/log_file.h [hunk 17]
```diff
@@ -0,0 +1,259 @@
+/*
+ * This header is internal to log_control.c and should not
+ * be included elsewhere
+ */
+
+#ifndef ARDOP_COMMON_LOG_FILE_H_
+#define ARDOP_COMMON_LOG_FILE_H_
+
+ // for localtime_r()
+#define _POSIX_C_SOURCE 200809L
```
Comment (pflarue) [inline src/common/log_file.h]: With the other suggested changes, this is not required

File: src/common/log.c [hunk 18]
```diff
@@ -0,0 +1,318 @@
...
+	return ArdopLogDir;
+}
+
+void ardop_log_set_port(const uint16_t port) {
+	for (size_t i = 0; i < sizeof(ALL_LOG_FILES)/sizeof(ALL_LOG_FILES[0]); ++i) {
+		ALL_LOG_FILES[i]->port = port;
+	}
+}
+
+void ardop_log_set_level_console(const int level) {
```
Comment (pflarue) [inline src/common/log.c:212]: See note in HostInterface.c.  It might be useful to return a value from ardop_log_set_level_console() and ardop_log_set_level_file() to facilitate sending an appropriate response to the host program.

**Review by pflarue — CHANGES_REQUESTED** [review]
Lots of good work here.  Thanks for the effort.

However, it doesn't produce UTC timestamps on Windows.  Via the comments, I've proposed an alternative that uses zf_log.c from the time-utc-option branch of https://github.com/pflarue/zf_log.  If we move forward with this, I intend to submit this change to zf_log as a pull request to to the parent repository.  Whether it is accepted there or not, I think that it is a good solution for use by ardopcf.

My comments similarly describe replacing the change to TZ and use of localtime_r() with gmtime() for a better solution in the couple of spots where a UTC date/time are used other than in zf_log.c. 

I've suggested some changes to zf_log format descriptors and removal of `_UTC` from the log file name.

A few other minor changes.

**Comment by cbs228** [comment]
> However, it doesn't produce UTC timestamps on Windows. Via the comments, I've proposed an alternative that uses zf_log.c from the time-utc-option branch of https://github.com/pflarue/zf_log.

I think your patch is a great alternative implementation, but I would like to investigate this issue a bit more first.

I suspect that the Windows API function [`GetLocalTime()`](https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getlocaltime) from [zf_log.c:799](https://github.com/wonder-mice/zf_log/blob/5a3f2b46c3f62b97e2b33fbdb9d391abb64644f7/zf_log/zf_log.c#L799) does not respect the value of `TZ`. If it does, the Windows documentation makes no mention of this. I believe that Windows doesn't really have the notion of a "process-specific time zone."

Do the log filename timestamps work correctly? Are they UTC? Is it only the zf_log timestamps which are wrong? This old [sample program](https://sourceforge.net/p/mingw/mailman/message/15863872/) from 2005 suggests that MinGW's CRT should handle `TZ` "the POSIX way."

If it's only zf_log that is wrong, we can override `g_time_cb` to inject our own version of this function which uses the MinGW `localtime_r()`. If that works, there will be no need to patch zf_log. The result won't be usable with MSVC, but we've already committed to supporting MinGW only.

**Comment by pflarue** [comment]
I compiled ardopcf on Windows using the the code from cbs228:feature/zf_log.  By adjusting my windows system clock to late in the day so that the UTC date does not match my local date, I confirmed that while the timestamp values written to the log are in local time, the date values used for the filename of the log file are in UTC.

While this observation may allow a different solution than the one I proposed, I still think that my solution is a good choice.  Since we want UTC, using functions that provide it directly seems more straight forward than setting a process specific TZ value and then using functions intended to provide local time values.  If you feel strongly that we should avoid modifying zf_log, please explain why.  If zf_log was still being actively updated, and my changes were not accepted into the main code base, then I could understand such reluctance since it might complicate keeping a local copy of zf_log up to date with future improvements to zf_log.  However, the last change to zf_log was five years ago, so this doesn't seem to be relevant.

I agree that ardopcf is committed to only supporting MinGW for windows builds.  Doing so has allowed some simplification of the code base while providing a simple method for windows users to build from source should they wish to do so.  Thus, I continue to believe that this was a good choice.  Based on downloads of the last release of ardopcf, most users are running Linux, but I'm committed to continuing to also support Windows users.

**Comment by cbs228** [comment]
> the timestamp values written to the log are in local time, the date values used for the filename of the log file are in UTC

Thanks for testing this. I think this confirms my suspicions about `GetLocalTime()`.

> Since we want UTC, using functions that provide it directly seems more straight forward than setting a process specific TZ value and then using functions intended to provide local time values.

I prefer UTC as well, but I also want to avoid forcing a timezone or other locale behavior on the user. Using `localtime` and friends permit us to make the timezone runtime-selectable. This MR does not add such an option, but it leaves the door open for us to do so.

Food for thought:

* js8call uses only UTC, everywhere
* fldigi links both localtime and gmtime, but it appears to use only UTC as far as I can determine
* xastir displays only local time. xastir is mostly intended for VHF as opposed to HF
* pat logs only in local time

If you'd like to force UTC for everyone, everywhere, I'll go ahead and use your patch. If not, have a look at b8d09be642b48006b2a69e741f6d8118349e5168, which should fix the problem on Windows. Let me know which one of these you prefer and it'll be in the next revision.

There's only one other item from the review that I think needs more discussion. w.r.t. the host interface changes,

> While I'm OK with changing the level to what is probably a reasonable value, I'd prefer to also send an error to the host program.

To me, the presence of FAULT implies that the command did not complete. I'm not sure it's a good idea to both issue a FAULT **and** do something else instead (i.e., set a different log level). More importantly, I think that introducing an error message for previously acceptable input should itself be considered breaking behavior.

I can find no mention of `CONSOLELOG` or `LOGLEVEL` in the [2017 Host Interface Spec](https://www.winlink.org/sites/default/files/downloads/ardop_tnc_host_mode_interface_spec.pdf). We *could* elect to treat these as non-standard commands which are subject to revision across minor, rather than major, releases. Then perhaps the cleaner thing to do would be to just realign the  `LOGLEVEL` numerics with zf_log's logging levels. This is still breaking, but I think it's a less "hacky" approach. If we adopt the zf_log levels, we can just remove `ardop_log_verbosity_to_level()` and the legacy log levels altogether. WDYT?

**Comment by pflarue** [comment]
I don't see the ability to choose between UTC and local time as a feature with much real value.  So, I'm not interested in making design choices to accommodate it as a possible future feature.  Let's stay with only UTC.

I also don't particularly like the "hacky" conversion between ardop's traditional log levels and those used by zf_log.  When I saw this in the pull request, I also considered proposing that we simply adopt the zf_log level values natively.  Before doing so, I looked to see whether any host programs were actually using these.  I found no use of LOGLEVEL or CONSOLELOG in Pat.  While arim and garim don't use them internally, they have a `tnc-init-cmd` configuration option to allow users to send arbitrary host commands to ardop on startup.  Using this to set ardop's LOGLEVEL was specifically recommended in some announcements for these programs.  So, I decided to accept it as written.

However, following your last comment, I reviewed where I those references to LOGLEVEL.  I found that it was specifically suggested for use with TNC-Pi9k6.  So, it probably has limited usage.  Given all that, I think that adopting the zf_log levels natively as parameters to the LOGLEVEL and CONSOLELOG host commands is a good idea.  With this change, let's also adopt your approach of setting them to the min or max valid level if a value outside the available range is given.  However, a response of the form "LOGLEVEL now 4" should always be sent to the host indicating that the change has been made.  This is currently missing.

For most users, this change will only require adjustment to the command line usage, which I've already moved toward with my deprecation of some arguments.

File: src/common/HostInterface.c (hunk 6 above)
Comment (cbs228) [reply src/common/HostInterface.c:448]: 40ac8f591748652a6741afd2a459ce8e09fd78f6 migrates from legacy log levels to zf_log levels. The host interface should now report `CONSOLELOG now x`.

File: src/common/HostInterface.c (hunk 7 above)
Comment (cbs228) [reply src/common/HostInterface.c:796]: 40ac8f591748652a6741afd2a459ce8e09fd78f6 migrates from legacy log levels to zf_log levels. The host interface should now report `FILELEVEL now x`.

File: src/common/log.c (hunk 18 above)
Comment (cbs228) [reply src/common/log.c:212]: 40ac8f591748652a6741afd2a459ce8e09fd78f6 migrates from legacy log levels to zf_log levels. A return value proved unnecessary, but we can still add one if you want.

**Review by cbs228 — COMMENTED** [review]
This is ready for re-review. You'll probably get a few more email notifications for other threads because the github review tool simply can't cope with this many diffs.

File: src/common/log.c (hunk 11 above)
Comment (cbs228) [reply src/common/log.c]: I have applied this fix. I have also removed the source file information from the log file output.

File: src/common/log_file.c (hunk 16 above)
Comment (cbs228) [reply src/common/log_file.c]: We should prefer `gmtime_r()` over `gmtime()` since it is MT-safe (multithread safe). Granted, we're not writing a thread-safe logger, but I see little reason to add gotchas for future me.

I have removed the time zone from log file names.

File: src/common/log_file.h (hunk 17 above)
Comment (cbs228) [reply src/common/log_file.h]: I believe this is still required for `gmtime_r()`.

File: src/common/log.h (hunk 15 above)
Comment (cbs228) [reply src/common/log.h]: I believe this is still required for `gmtime_r()`.

**Comment by cbs228** [comment]
Ooops, also had to fix the deprecation warning for the CLI. This should now be ready.

File: src/common/log_file.c (hunk 16 above)
Comment (pflarue) [reply src/common/log_file.c]: Personally, I think this is a pointless choice, but I don't think it hurts anything.  So, I'll accept it.  gmtime() is being used elsewhere [ALSASound.c:StartTxWav())] and ardopcf is unlikely to ever be a multithreaded program.  A multithreaded version would allow complete restructuring of the RX and TX audio signal processing paths.  Thus, to properly take advantage of multithreading would be a major rewrite, at which point it probably makes sense to build a completely new program.

File: src/common/log.c (hunk 18 above)
Comment (pflarue) [reply src/common/log.c:212]: I agree.  With the new implementation, it isn't needed.

File: src/common/log.c [hunk 19]
```diff
@@ -0,0 +1,267 @@
...
+
+/*
+ * Console log verbosity
+ */
+static int ArdopLogVerbosityConsole = ZF_LOG_INFO;
+
+/*
+ * File log verbosity
+ */
+static int ArdopLogVerbosityFile = ZF_LOG_INFO;
```
Comment (pflarue) [inline src/common/log.c]: Previously FileLogLevel had a default value of LOGDEBUG, and I think that was a good choice.  So, I think that ArdopLogVerbosityFile should be ZF_LOG_DEBUG rather than ZF_LOG_INFO.  If I understand these settings correctly, that means that _zf_log_global_output_lvl must also be set to ZF_LOG_DEBUG.

File: src/common/log.h [hunk 20]
```diff
@@ -0,0 +1,281 @@
...
+ *
+ * @param[in] port  TCP port number of the control port. If
+ *            zero, only console logging will be enabled.
+ */
+void ardop_log_set_port(const uint16_t port);
+
+/**
+ * @brief Set minimum significance level of console logs
+ *
+ * ARDOP log levels ranges from `ZF_LOG_VERBOSE` (`0`) to
```
Comment (pflarue) [inline src/common/log.h]: Comment incorrect: ZF_LOG_VERBOSE is 1, not 0.

File: src/common/log.h [hunk 21]
```diff
@@ -0,0 +1,281 @@
...
+ * the minimum significance required for console output.
+ *
+ * @see ardop_log_set_level_console
+ */
+int ardop_log_get_level_console();
+
+/**
+ * @brief Set minimum significance level of file logs
+ *
+ * ARDOP log levels ranges from `ZF_LOG_VERBOSE` (`0`) to
```
Comment (pflarue) [inline src/common/log.h]: Comment incorrect: ZF_LOG_VERBOSE is 1 not 0

**Comment by pflarue** [comment]
The handling of -v (--verboselog) and -V (--verboseconsole) do not match the description of these options defined in HelpScreen[].  They are described as providing incremental changes, not absolute values.  Since these were previously deprecated, I propose that we eliminate these two options now rather than modify them.  You previously advocated not deprecating these options.  Do you still feel that they are useful?

Whether these are removed or not, HelpScreen[] needs to be updated.  If retained, then the range of values for the LOGLEVEL and CONSOLELOG in the deprecation messages need to be adjusted.

File: src/common/HostInterface.c [hunk 22]
```diff
@@ -430,22 +429,15 @@ void ProcessCommandFromHost(char * strCMD)
 
 		if (ptrParams == 0)
 		{
-			sprintf(cmdReply, "%s %d", strCMD, ConsoleLogLevel);
+			snprintf(cmdReply, sizeof(cmdReply), "%s %d", strCMD, ardop_log_get_level_console());
 			SendReplyToHost(cmdReply);
 		}
 		else
 		{
-			i = atoi(ptrParams);
```
Comment (pflarue) [inline src/common/HostInterface.c:438]: If ptrParams is not a number, atoi(ptrParams) returns 0 which ends up setting ConsoleLogLevel to ZF_LOG_VERBOSE which is not desirable in most cases.  Consider using strtol() or some other alternative approach that detects a non-numerical value, in which case a Syntax Error should be sent  to the Host program.  Also for LOGLEVEL

**Comment by pflarue** [comment]
I think this is close to ready. 

See comments regarding a couple of minor edits, either eliminating or correcting the -v and -V options, and returning a Syntax error if the LOGLEVEL or CONSOLELOG commands are given with a non-numerical value.

**Comment by cbs228** [comment]
> You previously advocated not deprecating these options. Do you still feel that they are useful?

There are scenarios where it is undesirable for ardopcf to write log files. When ardopcf is running as a system service under systemd or SysV init, there is probably some other logging mechanism available—i.e., syslog. In this case, the user might want a log file, or they might just want syslog to take care of it. At present, the only way to disable log files is via `--verboselog`. Some log messages are written before the `-H` commands are processed. This forces the creation of a log file.

I am considering adding a Linux-only `--syslog` option that will completely replace the `log_callback()` with one that only uses syslog only. (No log files.) The output will be more tailored for syslog and/or systemd. This will be the subject of a follow-up MR.

We could also replace `-v` and `-V` with a `--no-log-file` option that starts with `ArdopLogFileEnabled = false`. `ArdopLogFileEnabled` is controlled by the standard `DEBUGLOG` host command, so a `DEBUGLOG` could turn it on again. That might be small enough to implement here in this MR, or we could defer it. Or not do it at all. My main goal is `--syslog`.

> I think this is close to ready.

I'll get the other things taken care of. If you're okay with the general concept of `--syslog`, I'll also remove `-v` and `-V`.

**Comment by pflarue** [comment]
Adding a --no-log-file option seems like a reasonable addition while removing  -v and -V.  Please also include a suitable single letter argument form to go with it and add a description to HelpScreen.

**Comment by cbs228** [comment]
978f6f6253fb..9d1a6c9066 should take care of all this. Ready for re-review.

* I have opted for `--nologfile` instead of `--no-log-file` for consistency with other options. No other options use middle-dashes.

* The short option for `--nologfile` is `-m`. There are only a handful of alphabet letters that we have not already used. I wanted to avoid clashes with uppercase options since sometimes upper vs. lowercase implies a negation or at least a relationship.

* In addition to fixing error-handling for `CONSOLELOG` and `LOGLEVEL`, I have also fixed `DEBUGLOG`.

* 32d053e1293c844dd33a3d19311c9054b1bdf7c8 adds a convenience wrapper around `strtol()` and some test-cases for it.

File: src/common/HostInterface.c [hunk 23]
```diff
@@ -109,21 +109,21 @@ void AddDataToDataToSend(UCHAR * bytNewData, int Len)
...
 {
 	char cmdReply[128];
 
 	if (ptrParams == NULL)
 	{
-		sprintf(cmdReply, "%s %s", strCMD, (*Value) ? "TRUE": "FALSE");
+		snprintf(cmdReply, sizeof(cmdReply), "%s %s", strCMD, (*Value) ? "TRUE" : "FALSE");
 		SendReplyToHost(cmdReply);
-		return;
+		return false;
```
Comment (pflarue) [inline src/common/HostInterface.c:146]: While you didn't document what the return value of DoTrueFalseCmd() is intended to indicate, I think you meant for false to indicate an Error.  If that is your intent, it should return True when ptrParams == NULL.

File: src/common/HostInterface.c [hunk 24]
```diff
@@ -528,7 +525,16 @@ void ProcessCommandFromHost(char * strCMD)
...
+		BOOL enable_files = ardop_log_is_enabled_files();
+		if (DoTrueFalseCmd(strCMD, ptrParams, &enable_files)) {
+			ardop_log_enable_files((bool)enable_files);
+			snprintf(cmdReply, sizeof(cmdReply), "%s now %d", strCMD, enable_files);
+			ZF_LOGI("DEBUGLOG now %d", enable_files);
+			SendReplyToHost(cmdReply);
+		}
+		else {
+			snprintf(strFault, sizeof(strFault), "Syntax Err: %s %s", strCMD, ptrParams);
+		}
```
Comment (pflarue) [inline src/common/HostInterface.c]: DoTrueFalseCmd already did SendReplyToHost() or set strFault.  As written, this sends duplicates, and this SendReplyToHost produces "DEBUGLOG now 1" or "DEBUGLOG now 0" whereas DoTrueFalseCmd() produces the better "DEBUGLOG now TRUE" or "DEBUGLOG now FALSE".

See also the comment on return value from DoTrueFalseCmd.  As written, it sends "FAULT Syntax Err: DEBUGLOG (null)" as well as the correct response of "DEBUGLOG TRUE" or "DEBUGLOG FALSE" when no parameter is provided with a DEBUGLOG command.

File: test/ardop/test_log.c [hunk 25]
```diff
@@ -0,0 +1,239 @@
...
+	return (FILE*)mock();
+};
+
+FILE* __wrap_freopen(
+	const char* restrict pathname,
+	const char* restrict mode,
+	FILE* restrict handle
+) {
+	check_expected(pathname);
+	return (FILE*)mock();
```
Comment (pflarue) [inline test/ardop/test_log.c]: When compiling for 32-bit Linux or Windows (mingw32-make), lines 26 and 35 produce:
warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]

Seems to work though.

**Comment by pflarue** [comment]
Found a couple of minor issues relating to DoTrueFalseCmd() with DEBUGLOG host command.

Also a compiler warning that is only produced when compiling for 32-bit Linux or Windows.

File: src/common/HostInterface.c (hunk 23 above)
Comment (cbs228) [reply src/common/HostInterface.c:146]: That's not the intent of the new return value. The return value merely indicates if the client has provided a command which updates `*Value`. I added some function documentation for this.

File: src/common/HostInterface.c (hunk 24 above)
Comment (cbs228) [reply src/common/HostInterface.c]: Sure enough. I have put the DEBUGLOG logic back the way it was before.

I have found an unrelated error-reporting bug in `DoTrueFalseCmd()` as it exists on develop. Due to conflicts, I'm going to wait until after this PR is merged to submit a fix for it.

File: test/ardop/test_log.c (hunk 25 above)
Comment (cbs228) [reply test/ardop/test_log.c]: This is because cmocka uses the "largest integral type" to communicate numbers across the mocking framework. On most 32-bit platforms, the pointer type is smaller than the largest integral type (usually 64 bits).

* Some of my test-cases inject mock pointer values.
* Sometimes we also check their values.

There should not be any problems from this since we widen valid pointers to 64 bits, then narrow them back down.

Regardless, I have fixed them with a combination of cmocka macros and changing how the some return values are used. ASAN remains happy with this fix on Linux 64.

**Comment by cbs228** [comment]
9d1a6c9066d4afb8d66e12eb3f204cb28c4f7c62..d86258776747d0ff68cb5ef2c0a53bad3a73aa32 ought to take care of this.

**Comment by pflarue** [comment]
Thanks for your effort on this.

I found only one remaining problem with this PR.  strFault[] was declared both as a global variable and as a local variable within ProcessCommandFromHost().  Thus, setting its value within DoTrueFalseCmd() did not have the intended effect within ProcessCommandFromHost().  So, I edited your feature/zf_log branch to eliminate the declaration within ProcessCommandFromHost() prior to merging this PR.  I believe that this fixes the problem.  If you'd prefer a different solution, feel free to submit an additional pull request.

**Comment by cbs228** [comment]
> strFault[] was declared both as a global variable and as a local variable within ProcessCommandFromHost()

Yes, that's the problem I found. I was actually going to do the opposite and just dispatch the FAULT message directly from `DoTrueFalseCmd()`, but your solution works too. Thanks for helping with this!
